name: CI Pipeline for Leire Fernandez

# Se ejecuta cuando hay un push a la rama master
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Ejecuci贸n de pruebas de calidad de c贸digo (mockeado)
      - name: Pruebas de SAST
        run: echo "Ejecuci贸n de pruebas de SAST"

      # Paso 2: Crear el archivo credentials.ini
      - name: Crear archivo de credenciales
        run: |
          echo "[credentials]" > credentials.ini
          echo "username=${{ secrets.USERNAME }}" >> credentials.ini
          echo "password=${{ secrets.PASSWORD }}" >> credentials.ini
        # Guardar credentials.ini como un artefacto opcionalmente
        continue-on-error: true

      # Paso 3: Construcci贸n de la imagen Docker
      - name: Build docker image
        run: docker build -t devops_ws . --tag devops-ws:$(date +%s)

